"""Builds render/avatars/sahurModel.ts from a sculpt of Tung Tung Tung Sahur (an STL, z up, facing -y,
standing on a display base).

    pip install numpy trimesh fast-simplification networkx scipy
    python packages/client/scripts/sahur-model.py path/to/tungtungtungsahur.stl

It drops the base, decimates to TRIANGLES (the avatar budget: a few times Elizabeth's 1,200), turns the
sculpt into the avatar's frame (y up, facing +z, feet at 0, HEIGHT tall), splits it into the parts the
avatar moves on their own (the body with its arms, the bat, each leg), and writes each part's vertices
in millimetres relative to its pivot, its triangles, and a cavity shade per vertex (how far the
surface there curves in: mouth lines, eye sockets, the sides of the nose), base64-encoded. Skin colour
and normals are worked out when the avatar is built. Eyeballs are not taken from the sculpt; the avatar
adds its own at EYES.
"""

from __future__ import annotations

import base64
import sys
from pathlib import Path

import fast_simplification
import numpy as np
import trimesh

TRIANGLES = 2500
HEIGHT = 3.2  # metres, feet to the top of the head
BASE_TOP = 8.05  # sculpt units: the top of the display base the figure stands on
HIP_Z = 44.5  # sculpt units: faces below this (and not the bat) are legs
HAND = np.array([-10.5, 5.0, 44.0])  # sculpt units: the right hand, where it grips the bat
BAT_TIP = np.array([-15.0, -22.0, 10.0])
EYES = [np.array([-7.0, 2.4, 104.5]), np.array([7.0, 2.4, 104.5])]  # eyeball centres
EYE_RADIUS = 4.0
OUT = Path(__file__).resolve().parents[1] / "src/render/avatars/sahurModel.ts"


def main(stl: str) -> None:
    mesh = trimesh.load(stl)
    v, f = mesh.vertices, mesh.faces
    mesh = trimesh.Trimesh(v, f[~(v[f][:, :, 2] <= BASE_TOP).all(axis=1)], process=True)
    mesh.remove_unreferenced_vertices()
    v, f = fast_simplification.simplify(
        mesh.vertices.astype(np.float32), mesh.faces.astype(np.int64), target_reduction=1 - TRIANGLES / len(mesh.faces)
    )
    mesh = trimesh.Trimesh(v, f, process=True)
    v, f = mesh.vertices, mesh.faces
    centroids = v[f].mean(axis=1)
    cavity = cavities(mesh)

    # The bat: whatever stays joined to its tip once the faces round the gripping hand are set aside.
    near_hand = np.linalg.norm(centroids - HAND, axis=1) < 5
    rest = trimesh.Trimesh(v, f[~near_hand], process=False)
    parts = trimesh.graph.connected_component_labels(rest.face_adjacency, node_count=len(rest.faces))
    tip_face = int(np.argmin(np.linalg.norm(rest.triangles_center - BAT_TIP, axis=1)))
    bat = np.zeros(len(f), bool)
    bat[np.flatnonzero(~near_hand)[parts == parts[tip_face]]] = True
    low = (centroids[:, 2] < HIP_Z) & ~bat
    # The sculpt's right is -x; the avatar's right is +x (it faces +z with x to its right).
    leg_r = low & (centroids[:, 0] < 0)
    leg_l = low & (centroids[:, 0] >= 0)
    body = ~(bat | leg_l | leg_r)

    scale = HEIGHT / (v[:, 2].max() - BASE_TOP)
    centre_y = 15.0  # the log's centre line, front to back, in sculpt units

    def avatar(p: np.ndarray) -> np.ndarray:
        """Sculpt units to avatar metres: y up, facing +z, feet at 0, centred on the log."""
        p = np.atleast_2d(p)
        return np.stack([-p[:, 0], p[:, 2] - BASE_TOP, -(p[:, 1] - centre_y)], axis=1) * scale

    hip_y = float(avatar(np.array([0, 0, HIP_Z]))[0, 1])
    pivots = {
        "body": np.array([0, hip_y, 0]),
        "bat": avatar(HAND)[0],
        "legL": np.array([float(avatar(v[f[leg_l]].reshape(-1, 3)).mean(axis=0)[0]), hip_y, 0]),
        "legR": np.array([float(avatar(v[f[leg_r]].reshape(-1, 3)).mean(axis=0)[0]), hip_y, 0]),
    }
    lines = [
        "// Generated by packages/client/scripts/sahur-model.py from a sculpt of Tung Tung Tung Sahur; don't edit.",
        "// Each part: vertices in millimetres relative to its pivot (Int16 x, y, z), triangles (Uint16),",
        "// both base64. Pivots, the hand and the eyes are in metres in the avatar's frame (feet at 0, facing +z).",
        "export const SAHUR_MODEL = {",
        f"  height: {HEIGHT},",
        f"  hip: {hip_y:.4f},",
        f"  hand: [{', '.join(f'{c:.4f}' for c in avatar(HAND)[0])}],",
        f"  eyes: [{', '.join('[' + ', '.join(f'{c:.4f}' for c in avatar(e)[0]) + ']' for e in EYES)}],",
        f"  eyeRadius: {EYE_RADIUS * scale:.4f},",
        "  parts: {",
    ]
    for name, mask in [("body", body), ("bat", bat), ("legL", leg_l), ("legR", leg_r)]:
        faces = f[mask]
        used, inverse = np.unique(faces, return_inverse=True)
        positions = np.round((avatar(v[used]) - pivots[name]) * 1000).astype("<i2")
        # Mirroring x also swaps right- for left-handed axes, so the sculpt's winding already faces out in
        # Babylon's left-handed frame.
        triangles = inverse.reshape(-1, 3).astype("<u2")
        shades = np.round(cavity[used] * 255).astype(np.uint8)
        lines += [
            f"    {name}: {{",
            f"      pivot: [{', '.join(f'{c:.4f}' for c in pivots[name])}],",
            f"      positions: '{base64.b64encode(positions.tobytes()).decode()}',",
            f"      indices: '{base64.b64encode(triangles.tobytes()).decode()}',",
            f"      cavity: '{base64.b64encode(shades.tobytes()).decode()}',",
            "    },",
        ]
        print(f"{name}: {len(faces)} triangles, {len(used)} vertices")
    lines += ["  },", "} as const;", ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


def cavities(mesh: trimesh.Trimesh) -> np.ndarray:
    """0 to 1 per vertex: how much its neighbours rise above its tangent plane, i.e. how deep a crease
    it sits in. Flat and bulging surface is 0."""
    normals = mesh.vertex_normals
    out = np.zeros(len(mesh.vertices))
    for i, neighbours in enumerate(mesh.vertex_neighbors):
        if not neighbours:
            continue
        d = mesh.vertices[neighbours] - mesh.vertices[i]
        lengths = np.linalg.norm(d, axis=1) + 1e-9
        out[i] = np.mean((d @ normals[i]) / lengths)
    return np.clip(out / 0.35, 0, 1)


if __name__ == "__main__":
    main(sys.argv[1])
