// Tiny pixel-art icons as inline SVGs, drawn from bitmap strings so they stay crisp at any
// size. '.' is empty; every other character is a pixel, with a CSS class per character so the
// stylesheet picks the colours.
const NS = 'http://www.w3.org/2000/svg';

export function pixelSvg(rows: string[], cls: string, classes: Record<string, string> = {}): SVGSVGElement {
  const svg = document.createElementNS(NS, 'svg');
  svg.setAttribute('viewBox', `0 0 ${rows[0].length} ${rows.length}`);
  svg.setAttribute('class', `pixel ${cls}`);
  rows.forEach((row, y) => {
    [...row].forEach((ch, x) => {
      if (ch === '.') return;
      const r = document.createElementNS(NS, 'rect');
      r.setAttribute('x', String(x));
      r.setAttribute('y', String(y));
      r.setAttribute('width', '1');
      r.setAttribute('height', '1');
      if (classes[ch]) r.setAttribute('class', classes[ch]);
      svg.append(r);
    });
  });
  return svg;
}

// 9x8 heart. '+' is the highlight.
export const HEART = [
  '.##...##.',
  '#+##.####',
  '#########',
  '#########',
  '.#######.',
  '..#####..',
  '...###...',
  '....#....',
];

// 8x8 dagger: blade from the top right ('#'), guard ('G'), hilt ('H').
export const KNIFE = ['......##', '.....###', '....###.', '...###..', 'GG###...', '.GG.....', 'HGG.....', 'H.......'];

// 8x8 skull with eye holes and teeth.
export const SKULL = ['..####..', '.######.', '##.##.##', '##.##.##', '########', '.######.', '..#.#.#.', '..#.#.#.'];

// 8x8 robot head: antenna, visor eyes, a mouth grille.
export const ROBOT = ['...##...', '...##...', '.######.', '#.#..#.#', '#.#..#.#', '#.####.#', '.#.##.#.', '.######.'];

// 24x12 Modal mark, traced from the brand SVG: two mirrored hexagons meeting at the notch,
// '#' the lit faces, 'd' the shaded bottom face. Rendered by mountPoweredBy() on the loading screen.
export const MODAL_LOGO = [
  '....######....######....',
  '....######....######....',
  '...########..########...',
  '...##################...',
  '..#####dddddddddd#####..',
  '.#####ddddd..ddddd#####.',
  '.#####dddd....dddd#####.',
  '#####ddddd....ddddd#####',
  '####ddddd......ddddd####',
  '.###ddddd......ddddd###.',
  '.##ddddd........ddddd##.',
  '..#dddd..........dddd#..',
];

// 36x40 Elizabeth, traced from the site icon (assets/elizabeth.ico): 'k' outline, 'c' body,
// 'w' eyes, 'o' beak and feet. Rendered by mountLoadingArt() above the loading screen's title.
export const ELIZABETH = [
  '....................................',
  '....................................',
  '..............kkkkcckkk.............',
  '............kkcccccccccck...........',
  '...........kccccccccccccck..........',
  '..........kccccccccccccccck.........',
  '..........kcckckckccccccccc.........',
  '.........kccckkkkkcccckkkkck........',
  '.........ccckkwwwkccckwwwkck........',
  '........kccckwwwwkccckwwwkkc........',
  '........kcccckwwkkccckwwwkcc........',
  '........cccccckkkkkkkkkkkkcc........',
  '.......kcccccccckooookkkcccc........',
  '.......kccccccckokkkkkokcccck.......',
  '.......kccccccckkooookkkcccc........',
  '.......kccccccckkooooookcccc........',
  '.......kcccccccckkkookkccccc........',
  '.......ccccccccccckkkccccccck.......',
  '......kccckcccccccccccccccccck......',
  '......kccckcccccccccccccccccck......',
  '.......ccckccccccccccccccccccck.....',
  '.......kcckcccccccccccccccccccc.....',
  '.......kcckkccccccccccccccckccck....',
  '.......kkcckccccccccccccccckkcck....',
  '.......kkkckccccccccccccccck.kck....',
  '.......kckkcccccccccccccccck..kk....',
  '.......kccccccccccccccccccck........',
  '.......kccccccccccccccccccck........',
  '.......kccccccccccccccccccck........',
  '.......kccccccccccccccccccck........',
  '.......kccccccccccccccccccck........',
  '........ccccccccccccccccccck........',
  '........kccccccccccccccccccc........',
  '........kccccccccccccccccccc........',
  '.........kcccccccccccccccccc........',
  '..........kccccccccckkkkkkcc........',
  '..........kkkccckkk...kookkk........',
  '.........kkkkkkk.....kokkokkk.......',
  '........kkkkkkkk.....kkk.kk.k.......',
  '....................................',
];

// Elizabeth's step, from ELIZABETH to the passing frame, where she stands evenly on both feet with
// both flippers in, a pixel higher: her swung-out flipper turns in against her side and her lifted
// foot comes down. The step on to her mirror image is these mirrored, in reverse (LoadingArt.ts).
export const ELIZABETH_STEP = [
  [
    '....................................',
    '....................................',
    '..............kkkkcckkk.............',
    '............kkcccccccccck...........',
    '...........kccccccccccccck..........',
    '..........kccccccccccccccck.........',
    '..........kcckckckccccccccc.........',
    '.........kccckkkkkcccckkkkck........',
    '.........ccckkwwwkccckwwwkck........',
    '........kccckwwwwkccckwwwkkc........',
    '........kcccckwwkkccckwwwkcc........',
    '........cccccckkkkkkkkkkkkcc........',
    '.......kcccccccckooookkkcccc........',
    '.......kccccccckokkkkkokcccck.......',
    '.......kccccccckkooookkkcccc........',
    '.......kccccccckkooooookcccc........',
    '.......kcccccccckkkookkccccc........',
    '.......ccccccccccccccccccccck.......',
    '......kccckcccccccccccccccccck......',
    '......kccckcccccccccccccccccck......',
    '.......ccckccccccccccccccccccck.....',
    '.......kcckcccccccccccccccccccc.....',
    '.......kcckkccccccccccccccckccck....',
    '.......kkcckccccccccccccccckkcck....',
    '.......kkkckccccccccccccccckkck.....',
    '.......kckkcccccccccccccccck.kk.....',
    '.......kccccccccccccccccccck........',
    '.......kccccccccccccccccccck........',
    '.......kccccccccccccccccccck........',
    '.......kccccccccccccccccccck........',
    '.......kccccccccccccccccccck........',
    '........ccccccccccccccccccck........',
    '........kccccccccccccccccccc........',
    '........kccccccccccccccccccc........',
    '.........kcccccccccccccccccc........',
    '..........kccccccccckkkkkkc.........',
    '..........kkkccckkk...kkkkk.........',
    '.........kkkkkkk.....kkkkkkk........',
    '........kkkkkkkk.....kkk.kk.........',
    '....................................',
  ],
  [
    '....................................',
    '....................................',
    '..............kkkkcckkk.............',
    '............kkcccccccccck...........',
    '...........kccccccccccccck..........',
    '..........kccccccccccccccck.........',
    '..........kcckckckccccccccc.........',
    '.........kccckkkkkcccckkkkck........',
    '.........ccckkwwwkccckwwwkck........',
    '........kccckwwwwkccckwwwkkc........',
    '........kcccckwwkkccckwwwkcc........',
    '........cccccckkkkkkkkkkkkcc........',
    '.......kcccccccckooookkkcccc........',
    '.......kccccccckokkkkkokcccck.......',
    '.......kccccccckkooookkkcccc........',
    '.......kccccccckkooooookcccc........',
    '.......kcccccccckkkookkccccc........',
    '.......ccccccccccccccccccccc........',
    '......kccckccccccccccccccccck.......',
    '......kccckccccccccccccccccck.......',
    '.......ccckccccccccccccccccccc......',
    '.......kcckcccccccccccccccckcck.....',
    '.......kcckkcccccccccccccccccc......',
    '.......kkcckcccccccccccccckkcck.....',
    '.......kkkckcccccccccccccckkkck.....',
    '.......kckkcccccccccccccccck.ck.....',
    '.......kccccccccccccccccccck.k......',
    '.......kccccccccccccccccccck........',
    '.......kccccccccccccccccccck........',
    '.......kccccccccccccccccccck........',
    '.......kccccccccccccccccccck........',
    '........ccccccccccccccccccc.........',
    '........kcccccccccccccccccc.........',
    '........kcccccccccccccccccc.........',
    '.........kccccccccccccccckc.........',
    '..........kccccccccccckkkk..........',
    '..........kkkccckkkcckkkkkk.........',
    '.........kkkkkkk....kkkkkkk.........',
    '........kkkkkkkk.....kkk.kk.........',
    '....................................',
  ],
  [
    '....................................',
    '....................................',
    '.............kkkkcckkk..............',
    '...........kkcccccccccck............',
    '..........kccccccccccccck...........',
    '.........kccccccccccccccck..........',
    '.........kcckckckccccccccc..........',
    '........kccckkkkkcccckkkkck.........',
    '........ccckkwwwkccckwwwkck.........',
    '.......kccckwwwwkccckwwwkkc.........',
    '.......kcccckwwkkccckwwwkcc.........',
    '.......cccccckkkkkkkkkkkkcc.........',
    '......kcccccccckooookkkcccc.........',
    '......kccccccckokkkkkokcccck........',
    '......kccccccckkooookkkcccc.........',
    '......kccccccckkooooookcccc.........',
    '......kcccccccckkkookkccccc.........',
    '......ccccccccccccccccccccc.........',
    '......kccckccccccccccccccccck.......',
    '......kccckccccccccccccccccck.......',
    '.......ccckcccccccccccccccccc.......',
    '.......kcckccccccccccccccccccck.....',
    '.......kcckkcccccccccccccccccc......',
    '.......kkcckcccccccccccccckkcck.....',
    '.......kkkckccccccccccccckkkck......',
    '.......kckkcccccccccccccckckck......',
    '.......kccccccccccccccccccckkk......',
    '.......kccccccccccccccccccck........',
    '.......kccccccccccccccccccck........',
    '.......kccccccccccccccccccck........',
    '.......kccccccccccccccccccck........',
    '........ccccccccccccccccccc.........',
    '........kccccccccccccccccck.........',
    '........kcccccccccccccccccc.........',
    '.........kccccccccccccccck..........',
    '..........kccccccccccccck...........',
    '..........kkkccckkkccckkk...........',
    '.........kkkkkkk...kkkkkkk..........',
    '........kkkkkkkk....kkkkkkk.........',
    '....................................',
  ],
  [
    '....................................',
    '.............kkkkcckkk..............',
    '...........kkcccccccccck............',
    '..........kccccccccccccck...........',
    '.........kccccccccccccccck..........',
    '.........kcckckckccccccccc..........',
    '........kccckkkkkcccckkkkck.........',
    '........ccckkwwwkccckwwwkck.........',
    '.......kccckwwwwkccckwwwkkc.........',
    '.......kcccckwwkkccckwwwkcc.........',
    '.......cccccckkkkkkkkkkkkcc.........',
    '......kcccccccckooookkkcccc.........',
    '......kccccccckokkkkkokcccck........',
    '......kccccccckkooookkkcccc.........',
    '......kccccccckkooooookcccc.........',
    '......kcccccccckkkookkccccc.........',
    '......ccccccccccccccccccccc.........',
    '......kccckccccccccccccckccck.......',
    '......kccckccccccccccccckccck.......',
    '.......ccckccccccccccccckccc........',
    '.......kcckccccccccccccckcck........',
    '.......kcckkccccccccccckkcck........',
    '.......kkcckccccccccccckcckk........',
    '.......kkkckccccccccccckckkk........',
    '.......kckkccccccccccccckkck........',
    '.......kccccccccccccccccccck........',
    '.......kccccccccccccccccccck........',
    '.......kccccccccccccccccccck........',
    '.......kccccccccccccccccccck........',
    '.......kccccccccccccccccccck........',
    '........ccccccccccccccccccc.........',
    '........kccccccccccccccccck.........',
    '........kccccccccccccccccck.........',
    '.........kccccccccccccccck..........',
    '..........kccccccccccccck...........',
    '..........kkkccckkkccckkk...........',
    '.........kkkkkkk...kkkkkkk..........',
    '........kkkkkkkk...kkkkkkkk.........',
    '....................................',
    '....................................',
  ],
];
